seed: 1

dataset:
  path: /scratch/jreymond/unet_subset
  lens: ground_truth
  lensless: diffuser

  psf: data/psf/tape_rgb.png
  
  n_files: null    # null to use all 
  batch_size: 4
  validation_split: 0.2
  
  

device_conv: "cuda"    # "cuda" or "cpu"
save: False


train_params:
  epochs: 10
  lpips_model: "alex"
  


unet:

  bn_eps: 0.0001


