name: flatnet_model


enhancer:
  unet32:
    name : unet32
    enc_filters : [32, 64, 128, 256]
    last_conv_filter: 12

  unet64:
    name : unet64
    enc_filters : [64, 128, 256, 512]
    last_conv_filter: 12

  unet128:
    name : unet128
    enc_filters : [128, 256, 512, 1024]
    last_conv_filter: 12