  
name: 'flatnet'
path: /scratch/jreymond/flatnet
psf_path: 
truth_folder: 'groundtruth'
measure_folder: 'measurements_cropped'
truth_format: JPEG
measure_format: png
len: 10000

# if use the preprocessed dataset
# use_cropped_dataset : True
# measure_cropped_folder: measurements_cropped

mask_path : 'TODO'

calibrated_path: '/scratch/jreymond/flatnet/Initialization matrices/flatcam_prototype2_calibdata.mat'
random_toeplitz_path: 
  phi_l: '/scratch/jreymond/flatnet/Initialization matrices/phil_toep_slope22.mat'
  phi_r: '/scratch/jreymond/flatnet/Initialization matrices/phir_toep_slope22.matt'


# psf:
#   path: "TODO"
#   height: 1280 
#   width: 1408
#   crop_size_x: 1280 
#   crop_size_y: 1408 
#   centre_x: 808
#   centre_y: 965

# raw_truth_height: 344
# raw_truth_width: 379
# For resizing w.r.t the FoV of the prototype
truth_height: 256
truth_width: 256
truth_channels: 3

raw_measure_height: 512
raw_measure_width: 640
# after cropping
measure_height: 500
measure_width: 620

# Bayer measurements
measure_channels: 4

rotate_measurements: True

center_crop : False

type_mask: "separable"

padding: False
# meas = measure
crop:
  measurements:
    low_h: 6 
    high_h: 506
    low_w: 10 
    high_w: 630
    size_h: 500 
    size_w: 620 

  

