  
name: 'flatnet'
path: '/scratch/bezzam/ICCV-2019-FlatNet-Dataset/Display-Captures'
psf_path: 
truth_folder: 'groundtruth'
measure_folder: 'measurements'
truth_format: JPEG
measure_format: png
len: 10000

mask_path : 'TODO'

# psf:
#   path: "TODO"
#   height: 1280 
#   width: 1408
#   crop_size_x: 1280 
#   crop_size_y: 1408 
#   centre_x: 808
#   centre_y: 965

# raw_truth_height: 344
# raw_truth_width: 379
# For resizing w.r.t the FoV of the prototype
truth_height: 256
truth_width: 256
truth_channels: 3

measure_height: 512
measure_width: 640
# Bayer measurements
measure_channels: 4

padding: False
# meas = measure
crop:
  measurements:
    low_h: 6 
    high_h: 506
    low_w: 10 
    high_w: 630
    size_h: 500 
    size_w: 620 

  

