  
name: 'phlatnet'


path: '/scratch/jreymond/phlatnet'
truth_folder: 'orig'

measure_folder: 'imagenet_caps_384_12bit_Feb_19'

# if use the preprocessed dataset
use_cropped_dataset : True
measure_cropped_folder: measures_cropped

truth_format: JPEG
measure_format: png
len: 9791 # normally 10000, but some measurements are not available

mask_path : 'TODO'

psf:
  path: /scratch/jreymond/phlatnet/phase_psf/psf.npy
  height: 1280 
  width: 1408
  crop_size_x: 1280 
  crop_size_y: 1408 
  centre_x: 808
  centre_y: 965

raw_truth_height: 344
raw_truth_width: 379
# For resizing w.r.t the FoV of the prototype
truth_height: 384
truth_width: 384
truth_channels: 3
# output of measurement after cropping
# measure_height: 1280
# measure_width: 1408
measure_height: 608
measure_width: 864
# Bayer measurements
measure_channels: 4

padding: True

type_mask: "non_separable"
  
rotate_measurements: False

# directly use measure as output shape
center_crop: True



crop:
  # center crop where center_h: 808 and center_w : 965
  measurements: 
    low_h: 168 
    high_h: 1448
    low_w: 261 
    high_w: 1669
    # must match the size involved by the cropping
    size_h: 1280 
    size_w: 1408 

