name: wallerlab
path: /scratch/jreymond/unet_subset
psf_path: data/psf/tape_rgb.png

truth_folder: ground_truth
measure_folder: diffuser
len: 7513
truth_format: numpy
measure_format: numpy

truth_height: 270
truth_width: 480
truth_channels: 3

measure_height: 270
measure_width: 480
measure_channels: 3

crop:

