name: wallerlab
path: /scratch/jreymond/unet_subset
psf_path: data/psf/tape_rgb.png

truth_folder: ground_truth
measure_folder: diffuser
len: 7513
truth_format: numpy
measure_format: numpy

height: 270
width: 480
truth_channels: 3
measure_channels: 3

crop:

