lensless:
  path: /scratch/jreymond/unet_subset
  psf_path: data/psf/tape_rgb.png
  psf_path: 
  shape: [270, 480]
  channels: 3
  len: 7513
  lens: ground_truth
  lensless: diffuser
  format: numpy
  prefix: im
  suffix: npy
  crop:



flatnet:
  path: 

