defaults:
  - dataset: flatnet_dataset
  - model: flatnet_model

  
batch_size: 8
validation_split: 0.2
epochs: 20
lpips_model: vgg
device_conv: cuda    # "cuda" or "cpu"

# TODO : not implemented  
greyscale: False

save: True
model_path: stored_models
model_name: u_net
use_tensorboard: True
temp_store_path: "temp"

use_crop: True
use_mask: False

seed: 1   # Note : will not result in a deterministic output if use cuda device

gaussian_noise: 0.005

wiener_gamma: 50000