
# need to define the dataset
defaults:
  - wallerlab_reconstruction.yaml

# camera_inversion_model: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26/tensorflow/models/camera_inversion.pb
# pruned
camera_inversion_model: /home/jreymond/lensless_ml/outputs/2023-06-26/18-50-57/tensorflow/models/camera_inversion.pb
# normal
# camera_inversion_model: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26/tensorflow/models/camera_inversion.pb
# qat
# camera_inversion_model: /home/jreymond/lensless_ml/outputs/2023-06-26/18-56-13/tensorflow/models/camera_inversion.pb
# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-26/18-56-13/tensorflow/models/perceptual_model.pb

# camera_inversion.pb  gen_unet64.pb  overal_model.pb  perceptual_model.pb  unet64.pb
# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-26/18-56-13/tensorflow/models/gen_unet64.pb

# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-22/09-24-19/tensorflow/models/gen_wallerlab_unet.pb


# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-02/10-40-15/tensorflow/models/overal_model.pb



# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-25/16-54-51/tensorflow/models/overal_model.pb





# perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26/tensorflow/models/perceptual_model.pb
# tflite_camera_inversion: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26/tflite/camera_inversion.tflite



# generated by train.py
# store_folder: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26

# pruned 
# store_folder: /home/jreymond/lensless_ml/outputs/2023-06-26/18-50-57
# normal
# store_folder: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26
# cluster
# store_folder: /home/jreymond/lensless_ml/outputs/2023-06-29/13-42-29
# store_folder: /home/jreymond/lensless_ml/temporary/cluster_128
# qat
# store_folder: /home/jreymond/lensless_ml/outputs/2023-06-26/18-56-13

# tflite_perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-26/18-56-13/tflite/qat.tflite

tflite_perceptual_model: /home/jreymond/lensless_ml/outputs/2023-06-23/07-02-26/tflite/normal_weight_quant.tflite





sample_images: True
sample_images_folder: /home/jreymond/lensless_ml/sample_imgs/wallerlab

name_final_folder: ground_truth


num_threads: 32