defaults:
  - dataset: wallerlab_dataset
  - model: wallerlab_unet

  
batch_size: 8
validation_split: 0.2
epochs: 100
lpips_model: alex
device_conv: cuda    # "cuda" or "cpu"
  
greyscale: False

save: True
model_path: stored_models
use_tensorboard: True
temp_store_path: "temp"

use_crop: False

seed: 1   # Note : will not result in a deterministic output if use cuda device
